title: Python (TI2)
email: maciej.dems@p.lodz.pl
description: >-
  Python dla fizyków i inżynierów
baseurl: ""
url: https://mds-python.github.io/

remote_theme: pmarsceill/just-the-docs
color_scheme: tul

markdown: kramdown

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

exclude:
  - html.sed
  - vendor
